/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as RegistratiRouteImport } from './routes/registrati'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NoteLegaliRouteImport } from './routes/note-legali'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ConvenzioniRouteImport } from './routes/convenzioni'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as CafPatronatoRouteImport } from './routes/caf-patronato'
import { Route as AplRouteImport } from './routes/apl'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotizieIndexRouteImport } from './routes/notizie/index'
import { Route as FormazioneIndexRouteImport } from './routes/formazione/index'
import { Route as FormazioneSlugRouteImport } from './routes/formazione/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistratiRoute = RegistratiRouteImport.update({
  id: '/registrati',
  path: '/registrati',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteLegaliRoute = NoteLegaliRouteImport.update({
  id: '/note-legali',
  path: '/note-legali',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvenzioniRoute = ConvenzioniRouteImport.update({
  id: '/convenzioni',
  path: '/convenzioni',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const CafPatronatoRoute = CafPatronatoRouteImport.update({
  id: '/caf-patronato',
  path: '/caf-patronato',
  getParentRoute: () => rootRouteImport,
} as any)
const AplRoute = AplRouteImport.update({
  id: '/apl',
  path: '/apl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotizieIndexRoute = NotizieIndexRouteImport.update({
  id: '/notizie/',
  path: '/notizie/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormazioneIndexRoute = FormazioneIndexRouteImport.update({
  id: '/formazione/',
  path: '/formazione/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormazioneSlugRoute = FormazioneSlugRouteImport.update({
  id: '/formazione/$slug',
  path: '/formazione/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apl': typeof AplRoute
  '/caf-patronato': typeof CafPatronatoRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/convenzioni': typeof ConvenzioniRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/note-legali': typeof NoteLegaliRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registrati': typeof RegistratiRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/formazione/$slug': typeof FormazioneSlugRoute
  '/formazione/': typeof FormazioneIndexRoute
  '/notizie/': typeof NotizieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apl': typeof AplRoute
  '/caf-patronato': typeof CafPatronatoRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/convenzioni': typeof ConvenzioniRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/note-legali': typeof NoteLegaliRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registrati': typeof RegistratiRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/formazione/$slug': typeof FormazioneSlugRoute
  '/formazione': typeof FormazioneIndexRoute
  '/notizie': typeof NotizieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apl': typeof AplRoute
  '/caf-patronato': typeof CafPatronatoRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/convenzioni': typeof ConvenzioniRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/note-legali': typeof NoteLegaliRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registrati': typeof RegistratiRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/formazione/$slug': typeof FormazioneSlugRoute
  '/formazione/': typeof FormazioneIndexRoute
  '/notizie/': typeof NotizieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apl'
    | '/caf-patronato'
    | '/chi-siamo'
    | '/contatti'
    | '/convenzioni'
    | '/cookie-policy'
    | '/note-legali'
    | '/privacy-policy'
    | '/registrati'
    | '/servizi'
    | '/sitemap.xml'
    | '/formazione/$slug'
    | '/formazione/'
    | '/notizie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apl'
    | '/caf-patronato'
    | '/chi-siamo'
    | '/contatti'
    | '/convenzioni'
    | '/cookie-policy'
    | '/note-legali'
    | '/privacy-policy'
    | '/registrati'
    | '/servizi'
    | '/sitemap.xml'
    | '/formazione/$slug'
    | '/formazione'
    | '/notizie'
  id:
    | '__root__'
    | '/'
    | '/apl'
    | '/caf-patronato'
    | '/chi-siamo'
    | '/contatti'
    | '/convenzioni'
    | '/cookie-policy'
    | '/note-legali'
    | '/privacy-policy'
    | '/registrati'
    | '/servizi'
    | '/sitemap.xml'
    | '/formazione/$slug'
    | '/formazione/'
    | '/notizie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AplRoute: typeof AplRoute
  CafPatronatoRoute: typeof CafPatronatoRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  ConvenzioniRoute: typeof ConvenzioniRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  NoteLegaliRoute: typeof NoteLegaliRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegistratiRoute: typeof RegistratiRoute
  ServiziRoute: typeof ServiziRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FormazioneSlugRoute: typeof FormazioneSlugRoute
  FormazioneIndexRoute: typeof FormazioneIndexRoute
  NotizieIndexRoute: typeof NotizieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrati': {
      id: '/registrati'
      path: '/registrati'
      fullPath: '/registrati'
      preLoaderRoute: typeof RegistratiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note-legali': {
      id: '/note-legali'
      path: '/note-legali'
      fullPath: '/note-legali'
      preLoaderRoute: typeof NoteLegaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convenzioni': {
      id: '/convenzioni'
      path: '/convenzioni'
      fullPath: '/convenzioni'
      preLoaderRoute: typeof ConvenzioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caf-patronato': {
      id: '/caf-patronato'
      path: '/caf-patronato'
      fullPath: '/caf-patronato'
      preLoaderRoute: typeof CafPatronatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apl': {
      id: '/apl'
      path: '/apl'
      fullPath: '/apl'
      preLoaderRoute: typeof AplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notizie/': {
      id: '/notizie/'
      path: '/notizie'
      fullPath: '/notizie/'
      preLoaderRoute: typeof NotizieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formazione/': {
      id: '/formazione/'
      path: '/formazione'
      fullPath: '/formazione/'
      preLoaderRoute: typeof FormazioneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formazione/$slug': {
      id: '/formazione/$slug'
      path: '/formazione/$slug'
      fullPath: '/formazione/$slug'
      preLoaderRoute: typeof FormazioneSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AplRoute: AplRoute,
  CafPatronatoRoute: CafPatronatoRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  ConvenzioniRoute: ConvenzioniRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  NoteLegaliRoute: NoteLegaliRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegistratiRoute: RegistratiRoute,
  ServiziRoute: ServiziRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FormazioneSlugRoute: FormazioneSlugRoute,
  FormazioneIndexRoute: FormazioneIndexRoute,
  NotizieIndexRoute: NotizieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
